#!/usr/bin/env nu

# Generates everything compose.yaml needs that must not be committed:
#   secrets/   SSH client keys, SSH host keys and the Jenkins admin password
#   .env       public keys, which compose passes to the containers
# Existing files are kept, so running it again is safe. Use --force to start over.

const here = path self | path dirname
const secrets = path self secrets

# client key pairs: who connects where
const client_keys = {
    jenkins_ssh_agent_key: "jenkins-controller -> ssh-agent (user jenkins)"
    jenkins_ansible_agent_key: "jenkins-controller -> ansible-agent (user jenkins)"
    ansible_test_server_key: "ansible -> test-server (user ansible)"
}

# host keys, so every SSH connection can verify who it is talking to
const host_keys = [ssh-agent ansible-agent test-server]

def keygen [file: string, comment: string] {
    if ($file | path exists) { return }
    ^ssh-keygen -q -t ed25519 -N "" -C $comment -f $file
    print $"created ($file | path relative-to $here)"
}

def host-key-file [host: string]: nothing -> string {
    $secrets | path join $"($host | str replace --all '-' '_')_host_key"
}

# the key without its comment: "ssh-ed25519 AAAA..."
def public-key [file: string]: nothing -> string {
    open --raw $"($file).pub" | str trim | split row " " | first 2 | str join " "
}

def main [
    --force  # delete secrets/ and .env first
] {
    if $force {
        rm --recursive --force $secrets ($here | path join ".env")
        print "removed secrets/ and .env"
    }

    mkdir $secrets
    chmod 700 $secrets

    for key in ($client_keys | transpose name comment) {
        keygen ($secrets | path join $key.name) $key.comment
    }
    for host in $host_keys {
        keygen (host-key-file $host) $"($host) host key"
    }

    let password_file = $secrets | path join "admin_password"
    if not ($password_file | path exists) {
        random chars --length 24 | save $password_file
        print "created secrets/admin_password"
    }

    # the controller runs as uid 1000 and reads these through bind mounts; with
    # rootless podman they show up as root-owned inside, so they must be world
    # readable. secrets/ itself stays 700, which keeps other host users out.
    for name in (($client_keys | columns) | append "admin_password") {
        chmod 644 ($secrets | path join $name)
    }
    # sshd refuses host keys that others can read
    for host in $host_keys {
        chmod 600 (host-key-file $host)
    }

    # the ansible agent verifies the test server against this
    $"test-server (public-key (host-key-file test-server))\n" | save --force ($secrets | path join "known_hosts")

    let env_file = $here | path join ".env"
    [
        "# generated by setup.nu, public values only"
        $"JENKINS_AGENT_SSH_PUBKEY=(public-key ($secrets | path join jenkins_ssh_agent_key))"
        $"ANSIBLE_AGENT_SSH_PUBKEY=(public-key ($secrets | path join jenkins_ansible_agent_key))"
        $"SSH_AGENT_HOST_KEY=(public-key (host-key-file ssh-agent))"
        $"ANSIBLE_AGENT_HOST_KEY=(public-key (host-key-file ansible-agent))"
    ] | str join "\n" | $in + "\n" | save --force $env_file
    print "wrote .env"

    print ""
    print "Jenkins login: admin / (open secrets/admin_password)"
    print "next: podman compose up -d --build"
}
