#!/usr/bin/env nu

const lab02 = path self ../lab02.nu

# used when a job's variables are not set
const defaults = {
    daily: {schedule: "0 6 * * *", base: "MDL", quote: "EUR", days: 1, offset: 1}
    weekly: {schedule: "0 17 * * 5", base: "MDL", quote: "USD", days: 7, offset: 1}
}

def fail [msg: string, help?: string] {
    if $help == null {
        error make --unspanned {msg: $msg}
    } else {
        error make --unspanned {msg: $msg, help: $help}
    }
}

def job-names []: nothing -> list<string> {
    let jobs = $env.JOBS? | default "daily weekly"
    let names = $jobs | split row --regex '[\s,]+' | where $it != ""
    for name in $names {
        if not ($name =~ '^[a-z][a-z0-9_]*$') {
            fail $"invalid job name '($name)' in JOBS" "use lowercase letters, digits and underscores"
        }
    }
    if ($names | is-empty) { fail "JOBS is empty" "set JOBS, e.g. JOBS=\"daily weekly\"" }
    $names
}

def int-var [var: string, value: any, min: int]: nothing -> int {
    let parsed = try { $value | into int } catch { null }
    if $parsed == null or $parsed < $min {
        fail $"($var) must be a whole number >= ($min), got '($value)'"
    }
    $parsed
}

# job settings from <NAME>_SCHEDULE, _BASE, _QUOTE, _DAYS, _OFFSET
def job-config [name: string]: nothing -> record {
    let prefix = $name | str upcase
    let fallback = $defaults | get --optional $name | default {days: 1, offset: 1}
    let get = {|key| $env | get --optional $"($prefix)_($key | str upcase)" | default ($fallback | get --optional $key) }

    for key in [schedule base quote] {
        if (do $get $key) == null {
            fail $"job '($name)' has no ($prefix)_($key | str upcase)" $"set ($prefix)_SCHEDULE, ($prefix)_BASE and ($prefix)_QUOTE"
        }
    }

    {
        name: $name
        schedule: (do $get schedule)
        base: (do $get base)
        quote: (do $get quote)
        days: (int-var $"($prefix)_DAYS" (do $get days) 1)
        offset: (int-var $"($prefix)_OFFSET" (do $get offset) 0)
    }
}

def log-file []: nothing -> string {
    $env.LOG_FILE? | default ($env.HOME | path join "cron.log")
}

# print a line and append it to the log file
def log [line: string] {
    print $line
    $line + "\n" | save --append (log-file)
}

# lab02 arguments for a job: one date, or a --from/--to range
def job-args [job: record]: nothing -> list<string> {
    let day = {|ago| (date now) - ($ago * 1day) | format date "%Y-%m-%d" }
    if $job.days == 1 {
        [$job.base $job.quote (do $day $job.offset)]
    } else {
        [$job.base $job.quote --from (do $day ($job.offset + $job.days - 1)) --to (do $day $job.offset)]
    }
}

# run one job now
def "main run" [name: string] {
    let job = job-config $name
    let args = job-args $job
    let now = date now | format date "%Y-%m-%dT%H:%M:%S%:z"
    log $"($now) [($name)] lab02 rate ($args | str join ' ')"

    let result = ^nu --no-config-file -c $"use ($lab02); lab02 rate ($args | str join ' ')" | complete
    let output = [$result.stdout $result.stderr] | str join "" | ansi strip | str trim
    if $output != "" { log $output }
    log $"($now) [($name)] exit ($result.exit_code)"
    exit $result.exit_code
}

# print the crontab generated from the environment
def "main crontab" []: nothing -> string {
    let tz = $env.TZ? | default "UTC"
    # plain loops, so config errors are not wrapped in closure errors
    mut lines = ["# generated by scheduler.nu" $"CRON_TZ=($tz)"]
    for name in (job-names) {
        let job = job-config $name
        $lines = $lines | append $"($job.schedule) nu ($env.CURRENT_FILE) run ($name)"
    }
    $lines | str join "\n" | $in + "\n"
}

# print every job's settings
def "main jobs" [] {
    mut jobs = []
    for name in (job-names) { $jobs = $jobs | append (job-config $name) }
    $jobs
}

# write the crontab, optionally run every job once, then hand over to supercronic
def "main start" [] {
    let crontab = $env.HOME | path join "crontab"
    main crontab | save --force $crontab
    print $"=== crontab \(($crontab)\) ==="
    print (open --raw $crontab)
    ^supercronic -no-reap -test $crontab

    if ($env.RUN_ON_START? | default "true") == "true" {
        print "=== running every job once (RUN_ON_START=true) ==="
        for name in (job-names) {
            # a failing job must not stop the scheduler from starting
            try { ^nu $env.CURRENT_FILE run $name }
        }
    }

    print $"=== starting supercronic, logging to (log-file) ==="
    exec supercronic -passthrough-logs -prometheus-listen-address 127.0.0.1 $crontab
}

def main [] {
    print "usage: scheduler.nu (start | run <job> | crontab | jobs)"
}
